const posts=[
{slug:"api-latency-spike",title:"How I Debugged a 3-Second API Latency Spike",excerpt:"A production API started timing out intermittently. No code had changed. Here is the investigation from first alert to root cause.",date:"18 June 2026",readTime:"7 min read",tags:["performance","debugging","api design"],body:`<p>Intermittent latency is difficult because the system often looks healthy by the time someone begins investigating it. The first task is therefore not to guess. It is to improve the evidence.</p><h2>Start with the boundary</h2><p>I compared request duration at the edge, inside the application and at the database. That separated network time from application time and quickly showed that the delay was being introduced after the request entered the service.</p><blockquote>The fastest route to a root cause is usually a better measurement boundary.</blockquote><h2>Follow the slow path</h2><p>The outliers shared one database access pattern. A query plan had changed as the table grew, producing occasional scans under a particular parameter distribution. The code had not changed, but the operating conditions had.</p><h2>The useful lesson</h2><p>Production failures do not require a deployment. Data volume, cardinality, queue depth and external dependencies are all capable of moving a system into a different regime.</p>`},
{slug:"systems-fail-predictably",title:"Designing Systems That Fail Predictably",excerpt:"Reliability improves when failure modes are explicit, observable and rehearsed before production finds them for you.",date:"12 June 2026",readTime:"6 min read",tags:["reliability","systems","architecture"],body:`<p>A reliable system is not one that never fails. It is one whose failures are bounded, visible and recoverable.</p><h2>Define the failure envelope</h2><p>Every dependency should have an explicit timeout, retry policy and fallback behaviour. Without those decisions, the platform still has a policy; it is simply accidental.</p><h2>Make degradation legible</h2><p>Operators need to know what has been lost, what remains safe and what action restores service. Good observability turns a confusing outage into a controlled response.</p>`},
{slug:"database-index-worse",title:"The Database Index That Made Everything Worse",excerpt:"Why a seemingly obvious Postgres optimisation increased write amplification and created a new bottleneck.",date:"3 June 2026",readTime:"8 min read",tags:["databases","postgres","performance"],body:`<p>An index can make one query fast while making the whole workload worse. This is especially true when the indexed columns change frequently.</p><h2>Optimise the workload, not the screenshot</h2><p>The new index improved a benchmark query, but increased write cost and vacuum pressure. Under sustained load, overall latency rose.</p><p>The right unit of optimisation was not a single query. It was the complete read and write workload.</p>`},
{slug:"engineering-operations",title:"What Good Engineering Operations Actually Look Like",excerpt:"Incident response, ownership and calm execution matter more than another dashboard full of green boxes.",date:"25 May 2026",readTime:"5 min read",tags:["operations","engineering culture","reliability"],body:`<p>Operational excellence is a behaviour before it is a tool. Clear ownership, useful escalation paths and honest post-incident analysis matter more than decorative reporting.</p>`},
{slug:"api-boundaries",title:"A Practical Guide to API Boundaries",excerpt:"How to draw service boundaries that are stable, understandable and resistant to organisational churn.",date:"17 May 2026",readTime:"7 min read",tags:["api design","architecture","systems"],body:`<p>Good boundaries follow durable business capabilities rather than temporary team structures. They reduce the number of facts each service must know about the rest of the system.</p>`},
{slug:"legacy-platform-migration",title:"Lessons From Migrating a Legacy Platform",excerpt:"The difficult parts were not the new tools. They were sequencing, trust and knowing what could not break.",date:"8 May 2026",readTime:"9 min read",tags:["architecture","operations","career"],body:`<p>Large migrations succeed when the cutover plan respects operational reality. A technically superior replacement is not useful if the transition creates unacceptable risk.</p>`}
];
const allTags=["all",...new Set(posts.flatMap(p=>p.tags))].sort((a,b)=>a==="all"?-1:b==="all"?1:a.localeCompare(b));
const $=s=>document.querySelector(s);
const escapeHtml=s=>s.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));

document.querySelectorAll("[data-year]").forEach(el=>el.textContent=new Date().getFullYear());
const menuButton=$(".menu-button"),nav=$("#primary-nav");
if(menuButton&&nav)menuButton.addEventListener("click",()=>{const open=nav.classList.toggle("open");menuButton.setAttribute("aria-expanded",String(open));});

function postUrl(post){return `post.html?slug=${encodeURIComponent(post.slug)}`}
function renderLatest(){const host=$("#latestPosts");if(!host)return;host.innerHTML=posts.slice(0,3).map(p=>`<a class="latest-card" href="${postUrl(p)}"><span class="meta">${escapeHtml(p.date)} / ${escapeHtml(p.tags[0].toUpperCase())}</span><h2>${escapeHtml(p.title)}</h2><p>${escapeHtml(p.excerpt)}</p><span class="read">READ ARTICLE →</span></a>`).join("")}

function setupWriting(){const list=$("#postsList"),tagList=$("#tagList"),count=$("#postCount"),empty=$("#emptyState"),input=$("#searchInput"),wrap=$("#searchWrap");if(!list)return;let active="all",query="";
 const renderTags=()=>{tagList.innerHTML=allTags.map(t=>`<button class="tag ${t===active?"active":""}" data-tag="${escapeHtml(t)}">${escapeHtml(t)}</button>`).join("");tagList.querySelectorAll(".tag").forEach(b=>b.addEventListener("click",()=>{active=b.dataset.tag;renderTags();renderPosts()}));};
 const renderPosts=()=>{const filtered=posts.filter(p=>(active==="all"||p.tags.includes(active))&&`${p.title} ${p.excerpt} ${p.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()));list.innerHTML=filtered.map((p,i)=>`<a class="post-link" href="${postUrl(p)}"><article class="post-item"><div class="post-number">${String(i+1).padStart(2,"0")}</div><div><h2>${escapeHtml(p.title)}</h2><p>${escapeHtml(p.excerpt)}</p></div><div class="post-arrow">→</div></article></a>`).join("");count.textContent=`${filtered.length} ${filtered.length===1?"post":"posts"}`;empty.style.display=filtered.length?"none":"block"};
 wrap.addEventListener("click",()=>{wrap.classList.add("expanded");input.focus()});input.addEventListener("input",e=>{query=e.target.value;renderPosts()});document.addEventListener("click",e=>{if(!wrap.contains(e.target)&&!input.value)wrap.classList.remove("expanded")});renderTags();renderPosts();}

function renderArticle(){const host=$("#article");if(!host)return;const slug=new URLSearchParams(location.search).get("slug");const post=posts.find(p=>p.slug===slug)||posts[0];document.title=`${post.title} — The Engineering Dispatch`;host.innerHTML=`<a class="back-link" href="writing.html">← ALL WRITING</a><header class="article-header"><div class="article-kicker">${escapeHtml(post.tags.join(" / ").toUpperCase())}</div><h1>${escapeHtml(post.title)}</h1><p class="article-deck">${escapeHtml(post.excerpt)}</p><div class="article-meta">${escapeHtml(post.date)} · ${escapeHtml(post.readTime)}</div></header><div class="article-body">${post.body}</div>`;}

renderLatest();setupWriting();renderArticle();
